yarnPath: .yarn/releases/yarn-2.4.1.cjs

packageExtensions:
  docker-image-name-parser@*:
    dependencies:
      tslib: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
