#
# Copyright (c) 2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: che-plugin-registry
  name: che-plugin-registry
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: che-plugin-registry
  strategy:
    type: RollingUpdate
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
  template:
    metadata:
      labels:
        app: che-plugin-registry
    spec:
      containers:
      - image: {{ .Values.chePluginRegistryImage }}
        imagePullPolicy: {{ .Values.chePluginRegistryImagePullPolicy }}
        name: che-plugin-registry
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /plugins/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /plugins/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          limits:
            memory: {{ .Values.chePluginRegistryMemoryLimit }}
          requests:
            memory: 256Mi
