apiVersion: v1
kind: Pod
metadata:
  name: happy-path-che
  namespace: iokhrime-che
spec:
  volumes:
    - name: test-run-results
  containers:
    # container containing the tests
    - name: happy-path-test
      image: quay.io/eclipse/che-e2e:nightly
      imagePullPolicy: Always
      env:
        - name: TS_SELENIUM_USERNAME
          value: admin
        - name: TS_SELENIUM_PASSWORD
          value: admin
        - name: TS_SELENIUM_VALUE_OPENSHIFT_OAUTH
          value: 'true'
        - name: TS_OCP_LOGIN_PAGE_PROVIDER_TITLE
          value: htpasswd
        - name: TS_SELENIUM_OCP_USERNAME
          value: admin
        - name: TS_SELENIUM_OCP_PASSWORD
          value: 'crw4ever!'
        - name: TEST_SUITE
          value: test-plugin
        - name: USERSTORY
          value: VscodeXmlPlugin
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: TS_SELENIUM_BASE_URL
          value: 'https://che-iokhrime-che.apps.ocp46.crw-qe.com'
        - name: TS_SELENIUM_LOG_LEVEL
          value: DEBUG
        - name: USERSTORY
          value: VscodeXmlPlugin
        - name: TS_SELENIUM_MULTIUSER
          value: 'true'
        - name: TS_SELENIUM_VALUE_TLS_SUPPORT
          value: 'true'
        - name: TS_SELENIUM_W3C_CHROME_OPTION
          value: 'true'          
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
      resources:
        requests:
          memory: "4Gi"
          cpu: "1000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"        
        # requests:
        #   memory: "8Gi"
        #   cpu: "3"
        # limits:
        #   memory: "8Gi"
        #   cpu: "4"
# Download results          
    - name: download-reports
      image: eeacms/rsync
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
      command: ["sh"]
      args:
        [
          "-c",
          "while true; if [[ -f /tmp/done ]]; then exit 0; fi; do sleep 1; done",
        ]
  restartPolicy: Never
