apiVersion: v1
kind: Pod
metadata:
  name: happy-path-che
  namespace: devworkspace-project
spec:
  volumes:
    - name: test-run-results
  containers:
    # container containing the tests
    - name: happy-path-test
      image: quay.io/eclipse/che-e2e:latest
      imagePullPolicy: Always
      env:
        - name: TEST_SUITE
          value: test-plugin
        - name: USERSTORY
          value: VscodeYamlPlugin
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: TS_SELENIUM_BASE_URL
          value: CHE_URL
        - name: TS_SELENIUM_LOG_LEVEL
          value: DEBUG
        - name: USERSTORY
          value: VscodeYamlPlugin
        - name: TS_SELENIUM_MULTIUSER
          value: false
        - name: TS_SELENIUM_VALUE_TLS_SUPPORT
          value: true
        - name: TS_SELENIUM_W3C_CHROME_OPTION
          value: true          
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
      resources:
        requests:
          memory: "20Gi"
          cpu: "3"
        limits:
          memory: "20Gi"
          cpu: "4"
# Download results          
    - name: download-reports
      image: eeacms/rsync
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
      command: ["sh"]
      args:
        [
          "-c",
          "while true; if [[ -f /tmp/done ]]; then exit 0; fi; do sleep 1; done",
        ]
  restartPolicy: Never
