apiVersion: v1
kind: Pod
metadata:
  name: happy-path-che
  namespace: devworkspace-project
spec:
  volumes:
    - name: test-run-results
  containers:
    # container containing the tests
    - name: happy-path-test
      image: quay.io/sskoryk/e2e:latest
      imagePullPolicy: Always
      env:
        - name: TEST_SUITE
          value: test-devworkspace-happy-path
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: TS_SELENIUM_BASE_URL
          value: CHE_URL
        - name: TS_SELENIUM_DEVWORKSPACE_URL
          value: WORKSPACE_ROUTE
        - name: TS_SELENIUM_LOG_LEVEL
          value: DEBUG
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
      resources:
        requests:
          memory: "900Mi"
          cpu: "250m"
        limits:
          memory: "900Mi"
          cpu: "700m"
# Download results          
    - name: download-reports
      image: eeacms/rsync
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: test-run-results
          mountPath: /tmp/e2e/report/
      command: ["sh"]
      args:
        [
          "-c",
          "while true; if [[ -f /tmp/done ]]; then exit 0; fi; do sleep 1; done",
        ]
  restartPolicy: Never
