const GET_CATLOG_ITEMS = 'GET_CATLOG_ITEMS';
const CREATE_CATALOG_INSTANCE = 'CREATE_CATALOG_INSTANCE';
const SHOW_CREATE_INSTANCE = 'SHOW_CREATE_INSTANCE';
const HIDE_CREATE_INSTANCE = 'HIDE_CREATE_INSTANCE';

const NAVIGATE_REQUEST = 'NAVIGATE_REQUEST';
const NAVIGATE_REQUEST_CLEAR = 'NAVIGATE_REQUEST_CLEAR';
const LOAD_PLUGINS_SUCCESS = 'LOAD_PLUGINS_SUCCESS';

export {
  GET_CATLOG_ITEMS,
  CREATE_CATALOG_INSTANCE,
  SHOW_CREATE_INSTANCE,
  HIDE_CREATE_INSTANCE,
  NAVIGATE_REQUEST,
  NAVIGATE_REQUEST_CLEAR,
  LOAD_PLUGINS_SUCCESS
};
