#
# Copyright (c) 2018-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-plugin-registry
  labels:
    app: che
    component: plugin-registry
    app.kubernetes.io/name: che
    app.kubernetes.io/component: plugin-registry
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: che
      component: plugin-registry
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: che
        component: plugin-registry
        app.kubernetes.io/name: che
        app.kubernetes.io/component: plugin-registry
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      containers:
      - image: {{ .Values.chePluginRegistryImage }}
        imagePullPolicy: {{ .Values.chePluginRegistryImagePullPolicy }}
        name: che-plugin-registry
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /v3/plugins/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /v3/plugins/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 3
        securityContext:
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: 500m
            memory: {{ .Values.chePluginRegistryMemoryLimit }}
          requests:
            cpu: 100m
            memory: 32Mi
        envFrom:
        - configMapRef:
            name: che-plugin-registry
            optional: true
