#
# Copyright (c) 2018-2023 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: che-plugin-registry
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: che-plugin-registry
    labels:
      app: che
      component: plugin-registry
      app.kubernetes.io/name: che
      app.kubernetes.io/instance: che
      app.kubernetes.io/component: plugin-registry
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: che
        component: plugin-registry
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    template:
      metadata:
        labels:
          app: che
          component: plugin-registry
          app.kubernetes.io/name: che
          app.kubernetes.io/instance: che
          app.kubernetes.io/component: plugin-registry
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: "${PULL_POLICY}"
          name: che-plugin-registry
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /v3/plugins/
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /v3/plugins/
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 10
          securityContext:
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: ${MEMORY_LIMIT}
          envFrom:
          - configMapRef:
              name: che-plugin-registry
              optional: true
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: che-plugin-registry
    labels:
      app.kubernetes.io/name: che
      app.kubernetes.io/instance: che
      app.kubernetes.io/component: plugin-registry
  spec:
    ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: che
      component: plugin-registry
- apiVersion: v1
  kind: Route
  metadata:
    name: che-plugin-registry
    labels:
      app.kubernetes.io/name: che
      app.kubernetes.io/instance: che
      app.kubernetes.io/component: plugin-registry
  spec:
    to:
      kind: Service
      name: che-plugin-registry
      weight: 100
    port:
      targetPort: 8080
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: che-plugin-registry
    labels:
      app.kubernetes.io/name: che
      app.kubernetes.io/instance: che
      app.kubernetes.io/component: plugin-registry
  data:
    START_OPENVSX: ${START_OPENVSX}

parameters:
- name: IMAGE
  value: quay.io/eclipse/che-plugin-registry
  displayName: Eclipse Che plugin registry image
  description: Che plugin registry Docker image. Defaults to eclipse/che-plugin-registry
- name: IMAGE_TAG
  value: next
  displayName: Eclipse Che plugin registry version
  description: Eclipse Che plugin registry version which defaults to next
- name: MEMORY_LIMIT
  value: 1024Mi
  displayName: Memory Limit
  description: Maximum amount of memory the container can use. Defaults 256Mi
- name: PULL_POLICY
  value: Always
  displayName: Eclipse Che plugin registry image pull policy
  description: Always pull by default. Can be IfNotPresent
- name: START_OPENVSX
  value: "false"
  displayName: Start embedded OpenVSX registry
  description: If true, an embedded OpenVSX registry will be started
