#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Dependabot-post-check
# dependabot is not handling Yarn v2/3, workarounding the PR
# https://github.com/dependabot/dependabot-core/issues/1297

permissions:
  contents: write

on:
  push:
    branches: [dependabot/npm_and_yarn/**]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Autofix lockfile
        run: |
          # restore yarn.lock from the previous commit
          git checkout HEAD^ -- yarn.lock
          # redo the yarn install step
          yarn install
        env:
          YARN_ENABLE_SCRIPTS: 0 # disable postinstall scripts
          YARN_ENABLE_IMMUTABLE_INSTALLS: false # allow to override yarn.lock files
      - name: Config Git
        run: |
          git config --global user.email "che-bot@eclipse.org"
          git config --global user.name "CHE Bot"
      - name: Commit changes
        run: |
          git add yarn.lock # only adding yarn.lock as not using zero-installs
          git commit --amend --no-edit
          git push -f
