name: CI
on:
  pull_request:
    branches: 
      - master
jobs:
  digest-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run script which checks container image digest
      run: |
        sudo pip install yq
        /bin/bash .ci/digest-validation-pr.sh
