#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: vscode-extension.json field validation

on:
  pull_request:
    paths:
    - 'vscode-extensions.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Check fields and verify validity
      run: |
        ./.ci/vscode-extensions-field-validation.sh
